config/routes.rb
Obieventures::Application.routes.draw do
  match '/home', to: 'static_pages#home', via: 'get'
  match '/submit', to: 'static_pages#submit', via: 'get' 
  resources :adventures #, except: [:destroy, :edit, :index]

  match '/adventures/:id/like', to: 'adventures#like', via: 'put'

	root 'static_pages#home'

  

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
	validates(:summary, presence: true, length: { minimum: 5 }, uniqueness: { case_sensitive: false })
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = Adventure.all
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  #Added by Adam. Stolen from http://archive.railsforum.com/viewtopic.php?id=46646.
  def like
    @adventure = Adventure.find(params[:id])
    #if statement eventually won't be needed
    if @adventure.likes == nil
      @adventure.likes = 0
    end
    #create an empty array labeled likes in the cookie if it doesn't exist
    #The following usage of ActiveSupport::JSON allows us to deal with arrays
    cookies.permanent[:likes] ||= ActiveSupport::JSON.encode([])
    likes = ActiveSupport::JSON.decode(cookies[:likes])
    #if the user has already liked the adventure, unlike it.
    if likes.include?(params[:id])
      likes.delete(params[:id])
      cookies[:likes] = ActiveSupport::JSON.encode(likes)
      @adventure.likes -= 1
      @adventure.save!
    #otherwise, like it and clear the marker from their cookie.
    else
      likes << params[:id]
      cookies[:likes] = ActiveSupport::JSON.encode(likes)
      @adventure.likes += 1
      @adventure.save!
    end
    #here there be majicks
    respond_to do |format|
      format.html {redirect_to :action=>'show'}
      #format.js
    end
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adventure }
      else
        format.html { render action: 'new' }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:summary, :details)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
before_filter :http_basic_authenticate

def http_basic_authenticate
  authenticate_or_request_with_http_basic do |username, password|
    username == "99username" && password == "password99"
  end
end
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def generate
        num = rand(19)+1
        #while (Adventure.find(num).summary != NULL) {
        Adventure.find(num).summary
  end


  def submit
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/adventures/_form.html.erb
<%= form_for(@adventure) do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<head> 
	<title>ADVENTURE PAGE</title>
</head>

<center><h1 class="title_display">Listing of Adventures!</h1></center>
<body><center>
<table>
  <thead>
    <tr>
	<br><br><br>
      <th id="titles">Summary</th>
      <th id="titles">Details</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= adventure.summary %></td>
        <td><%= adventure.details %></td>
        <td><%= link_to 'Show', adventure %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
        <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table></center>

<br>

<center><%= link_to 'New Adventure', new_adventure_path %></center>
</body>

app/views/adventures/new.html.erb
<div class="submit_box">
<center><h1>Submit your own adventures!</h1>
<br><p class="instructions" id="justify">
	In the first field, take a sentence or two to describe the adventure.  In the second, put more details about how one might accomplish the adventure, ex:
<br><br><strong>Summary:</strong> see a movie at the apollo.<br>
	<strong>Details:</strong> it's located at 19 E College St, Oberlin, and showtimes can be found http://www.tributemovies.com/cinema/Ohio/Oberlin/Apollo+Theatre/4490/ 
	<br><br>Please keep suggestions clean.
</p>
<br>
<%= render 'form' %>

<%= link_to 'Back', home_path %>
</div></center>
<p class="contact_us" id="footer">contact us: obieventures@gmail.com || <a href="http://cs.oberlin.edu/~smater">sam mater</a> || <a href="http://cs.oberlin.edu/~astaffor">adam stafford</a> || <a href="http://cs.oberlin.edu/~pbuser">paul buser</a> || 2013</p>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="display_box">
<p>
   Likes: <%= @adventure.likes %>
   <% cookies[:likes] ||= ActiveSupport::JSON.encode([]) %>
   <% likeStat = (ActiveSupport::JSON.decode(cookies[:likes]).include? (params[:id])) ? "Unlike" : "Like" %>
   <%= button_to "#{likeStat}", {:action => "like", :id => @adventure.id} , :method => :put %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @adventure.summary %>
</p>

<p>
  <strong>Details:</strong>
  <%= @adventure.details %>
</p>

<p>
<!--<%= link_to 'Edit', edit_adventure_path(@adventure) %> |-->
<%= link_to 'Back', home_path %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ObieVentures</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/static_pages/_adventure.html.erb
<% $the_adventure = Adventure.all.sample %>
<%= $the_adventure.summary %>
<h1>
	<%=
	unless $the_adventure.details == ""
		$the_adventure.details
	end
	%>
</h1>
<p>
   Likes: <%= 
		unless $the_adventure.likes == nil
		 $the_adventure.likes
		else
		 0
		end
	%>

	</p>
<p>
   <% cookies[:likes] ||= ActiveSupport::JSON.encode([]) %>
<% likeStat = (ActiveSupport::JSON.decode(cookies[:likes]).include? (params[:id])) ? image_tag('liked_zps4b7a586b.png') : image_tag('like_zpsde970af6.png') %>
   <%= link_to likeStat, {:controller => 'adventures', :action => "like" , :id => $the_adventure.id } , {:method => :put  } %>
</p>

app/views/static_pages/_footer.html.erb
<p class="contact_us" id="footer">contact us: <a href="mailto:obieventures@gmail.com">obieventures@gmail.com</a> || <a href="http://cs.oberlin.edu/~smater" target="_blank">sam mater</a> || <a href="http://cs.oberlin.edu/~astaffor" target="_blank">adam stafford</a> || <a href="http://cs.oberlin.edu/~pbuser" target="_blank">paul buser</a> || 2013</p>

app/views/static_pages/home.html.erb
<p class="title_display">OBIEVENTURES</p>
<div id="adventure_title">
	<%= render 'adventure' %>
</div>
<p>
	<a href="http://obieventures.cs.oberlin.edu/" class="classname">Generate an Adventure!</a>
</p>
<p>
	<%= link_to 'Submit Your Own Adventure!', new_adventure_path %>
</p>
<%= render 'footer' %>

app/views/static_pages/submit.html.erb
<h1>StaticPages#submit</h1>
<p>Find me in app/views/static_pages/submit.html.erb</p>